config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "user_weekly_quests/update"
  root "dashboard#index"
  get "dashboard", to: "dashboard#index", defaults: { format: :html }
  devise_for :users
  post "activate_title", to: "users#activate_title"
post "deactivate_title", to: "users#deactivate_title"

  # Classement
  resources :leaderboard, only: [ :index, :show ]

  # Gestion des utilisateurs
  resources :users, only: [ :index ]

  # Quêtes et progression
  resources :quests, only: [ :index, :show ]
  resources :user_quests, only: [ :update, :create, :destroy ]

  # Achats et paiements
  resources :purchases, only: [ :new, :create ] do
    collection do
      get "success"
      get "cancel"
    end
  end

  # Amis
  resources :friends, only: [ :index, :create, :destroy ] do
    collection do
      get :search  # ✅ Ajoute la recherche d'amis
    end
    member do
      post :accept
      delete :reject
    end
  end
  resources :user_weekly_quests, only: [:update]


  get 'profil', to: 'users#show', as: :user_profile

  # Admin
  namespace :admin do
    resources :quests, except: [ :show ]
    resources :users, only: [ :index, :edit, :update ]
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leveling App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all" %>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.js"></script>

  <%= javascript_importmap_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Leveling</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Quêtes", quests_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Boutique", new_purchase_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Classement", leaderboard_index_path, class: "nav-link" if user_signed_in? %>
          </li>
          <li class="nav-item">
            <%= link_to "Amis", friends_path, class: "nav-link" if user_signed_in? %>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to "Admin", admin_quests_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
  <%= link_to "Profil", user_profile_path, class: "nav-link" %>
</li>
            <li class="nav-item">
              <%= form_with url: destroy_user_session_path, method: :delete, local: true do %>
                <%= submit_tag "Déconnexion", class: "nav-link" %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  <script>
  console.log("🚀 Rails charge bien le JavaScript !");
</script>
</body>
</html>